server:
  port: 3344
  
spring:
  application:
    name: microservicecloud-config
  cloud: 
    config: 
      server: 
        git: 
          uri: https://github.com/yang-yonghao/microcloud-config.git #git@github.com/yang-yonghao/microcloud-config.git #GitHub上面的git仓库名字
          username: yang-yonghao
          password: Yyh900419